[tool.poetry]
name = "nattrs"
version = "0.1.0"
description = "Nested attributes that works with dictionaries and class instances interchangeably."
authors = ["Ludvig <mail@ludvigolsen.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
